version: '3.9'

services:
  web:
    build:
      context: ./web
    image: konektatu_web
    container_name: konektatu_web_1
    ports:
      - "8080:80"  # Web zerbitzarirako portua
      - "2222:22"  # SSH-rako portua (kontainer barruko 22ra mapeatuta)